config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    # member do
    #   delete 'delete_photo/:photo_id', action: 'delete_photo', as: 'delete_photo'
    # end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blog.rb
class Blog < ApplicationRecord
	enum status: {draft: 0, published: 1}
	extend FriendlyId
  	friendly_id :title, use: :slugged

		has_rich_text :body

		has_many :comments, as: :commentable, dependent: :destroy

		validates_presence_of :title, :body, :topic_id

	  belongs_to :topic
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy, :toggle_status]

  # In the layout directory use blog.html.erb
  layout "blog"

  #petergate's access control
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.all.order("created_at DESC").page(params[:page]).per(5)
    else
      @blogs = Blog.published.order("created_at DESC").page(params[:page]).per(5)
    end
    @page_title = "My Portfolio Blog"
  end

  # GET /blogs/1
  def show
    if logged_in?(:site_admin) || @blog.published?
    views = @blog.views + 1
    @blog.update(views: views)
    @comments = @blog.comments.order("created_at DESC")

    @num_comments = @blog.comments.count
    @blog.comments.each do |comment|
      @num_comments += comment.comments.count
    end
    @page_title = @blog.title
    @seo_keywords = @blog.body
  else
    redirect_to blogs_path, notice: "You are not authorised to access this page"
  end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      flash[:success] = 'Blog was successfully created.'
      redirect_to @blog
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      flash[:success] = 'Blog was successfully updated.'
      redirect_to @blog
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }

    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end
    redirect_to blogs_url, notice: 'Status has been updated'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      @blog = Blog.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blog_params
      params.require(:blog).permit(:title, :body, :topic_id)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
    <%= link_to blog.status, toggle_status_blog_path(blog) %> |
    <%= link_to 'Edit', edit_blog_path(blog) %> |
    <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    </p>
  <% end %>

  <p class="blog-text">
    <%= blog.body.to_plain_text.truncate_words(50) %>
    <%= link_to "continue reading", blog_path(blog) %>
  </p>
  <p class="blog-text">
    <small class="text-muted">
      <%= blog.updated_at.strftime("%A, %B, %e, %Y") %> |
      <%= pluralize(blog.views, "View") %> |
      <% @num_comments = blog.comments.count %>
      <% blog.comments.each do |comment| %>
        <% @num_comments += comment.comments.count %>
      <% end %>

     <%= pluralize(@num_comments, "Comment") %> |
     <% if logged_in?(:site_admin) %>
       <%= link_to "Delete", blog, method: :delete %>
     <% end %>
    </small>
  </p>
</div>

app/views/blogs/_form.html.erb
<%= form_with model: blog do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :topic_id %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                      {
                        selected: blog.topic.id,
                        include_blank: true
                      },
                      class: 'form-control'
      )
    %>
  </div>

  <div class="form-group">
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.rich_text_area :body, class: 'form-control', placeholder: "Body" %>
  </div>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">

  <%= render @blogs %>

  <%= paginate @blogs %>

</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h3><%= @blog.title %></h3>
  <p><%= @blog.topic.title %></p>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

  <p class="lead">
    <%= @blog.updated_at.strftime("%A, %B %e, %Y") %> | <%= pluralize(@blog.views, "View") %>
  </p>
  <hr class="my-4" />
  <div class="blog_body">
    <%= @blog.body %>
  </div>

  <div class="container">
    <%= render 'comments/form', commentable: @blog, local: Comment.new %>

    <div id="comment-pane">
        <% @comments.each do |comment| %>
        <%= render comment %>
        <% end %>
    </div>
  </div>

</div>