config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    # member do
    #   delete 'delete_photo/:photo_id', action: 'delete_photo', as: 'delete_photo'
    # end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :blog

  validates :content, presence: true, length: {maximum: 1000}

  after_create_commit { CommentBroadcastJob.perform_later(self) }
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_commentable, only: [:create]
  before_action :set_comment, except: [:create]

  def create
    @comment = @commentable.comments.build(comment_params)
    @comment.user = current_user
    @comment.reply = true if params[:comment_id]
    @comment.save
  end

  def edit

  end

  def update
    if @comment.edit_history == ''
      # if \n => replace \n with <br/><hr/>
      @comment.edit_history = 'Original: ' + @comment.body.body.to_plain_text + "\n"
    else
      @comment.edit_history = @comment.edit_history + 'Edit: ' + params[:comment][:body] + "\n"
    end
    @comment.update(comment_params)
  end

  def destroy
    @comment.destroy
  end

  def history

  end

 private

 def comment_params
   params.require(:comment).permit(:body)
 end

 def set_commentable
   if params[:comment_id]
     @commentable = Comment.find_by_id(params[:comment_id])
   elsif params[:blog_id]
     @commentable = Blog.friendly.find(params[:blog_id])
   end
 end

 def set_comment
   @comment = Comment.find(params[:id])
 end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="comment-container" id="comment-<%= comment.id %>">
  <div class="container">
    <%= render 'comments/comments', comment: comment, local: Comment.new %>

    <% unless comment.reply %>
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-8">
          <div class="comment-form-nested">
            <%= render 'comments/form', commentable: comment, local: Comment.new %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/comments/_comment_form.html.erb
<% unless current_user.is_a? GuestUser %>
  <%= form_for @comment, remote: true, url: '#' do |f| %>
    <div class="form-group">
      <%= f.label :content %>
      <%= f.text_area :content, class: 'form-control' %>
    </div>

    <%= f.submit 'Post Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

app/views/comments/_comments.html.erb
<div class="row">
    <div class="col-md-3">
        <div class="row">
            <div class="comment-timestamp" id="edit-history-text-<%= comment.id %>">
                <%= render 'comments/edit_history_text', comment: comment%>
            </div>
        </div>
    </div>

    <div class="col-md-2">
      <div class="row">
        <div class="comment-avatar">
            <%= gravatar_helper comment.user %>
        </div>
        <div class="col-md-8">
          <div class="comment-username">
              <%= comment.user.name%>
          </div>
        </div>

        <% if current_user && (current_user == comment.user || logged_in?(:site_admin))%>
          <div class="col-4 text-right" style="padding-right: 0;">
            <div class="button-group" role="group" aria-label="Edit and Delete Button Group">
              <%= link_to "Edit", edit_comment_path(comment), class: 'btn btn-warning', remote: true %>
              <%= link_to "Delete", comment, class:'btn btn-danger', method: :delete, remote: true %>
            </div>
          </div>
        <% end %>
    </div>
    <hr class="md-4">
    <div class="comment-body" id="comment-body-<%= comment.id %>">
        <%= comment.body %>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-3"></div>
  <div class="col-9">
    <div class="inner-comment-container" id="reply-<%=comment.id%>">
      <% comment.comments.each do |comment|%>
      <%= render comment %>
      <% end %>
    </div>
  </div>
</div>

<!-- Modal-->
<div class="modal fade" id="edit_history" tabindex="-1" role="dialog" aria-labelledby="Comment Edit History" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="edit_history_title">Edit History</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="edit-history-body">
        <%= render 'comments/edit_history', comment: comment %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/comments/_edit_history.html.erb
<%= comment.edit_history.gsub(/\n/, '<br/><hr/>').html_safe %>

app/views/comments/_edit_history_text.html.erb
<%= time_ago_in_words(comment.created_at) %> ago
<br />
<% edit_history = comment.edit_history == "" ? "" : "Last edited " + time_ago_in_words(comment.updated_at) + " ago" %>
<%= link_to(edit_history, 'javascript:;', data: {toggle: "modal", target: "#edit_history"})%>

app/views/comments/_form.html.erb
<% if current_user %>
  <div class="row">
      <div class="comment-form">
          <%= form_with model: [commentable, local] do |f| %>
          <div class="form-group">
              <%= f.rich_text_area :body, placeholder: "write a comment...", class:"reply-form-#{commentable.id}", id: f.object.object_id, method: :patch %>
              <br/>
              <%= f.submit "Post Comment", class:'btn btn-dark float-right' %>
          </div>
          <% end %>
      </div>
  </div>

  <script>
      $(document).on("turbolinks:load", function() {
          $(".trix-button-group--file-tools").remove();
          document.addEventListener("trix-file-accept", function(event) {
              event.preventDefault();
          });
      });
  </script>
<% end %>

app/views/comments/create.js.erb
if ("<%= @comment.reply %>" === 'true') {
    var comment_pane;

    if ("<%= @commentable.comments.count %>" === "0") {
        comment_pane = "#reply-container-<%=@commentable.id %>";
    } else {
        comment_pane = "#reply-<%=@comment.commentable_id %>";
    }

    $(comment_pane).append("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
} else {
    $("#comment-pane").prepend("<%= j render @comment %>");
    $(".reply-form-<%= @commentable.id %>").val('');
}
$('.trix-button-group--file-tools').remove();

app/views/comments/destroy.js.erb
$("#comment-<%= @comment.id %>").remove();

app/views/comments/edit.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= j render 'comments/form', commentable: @comment.commentable, local: @comment %>");
$(".trix-button-group--file-tools").remove();

app/views/comments/update.js.erb
$("#comment-body-<%= @comment.id %>").html("<%= raw @comment.body.body.to_html() %>");

$("#edit-history-body").html("<%= j render 'comments/edit_history', comment: @comment %>");

$("#edit-history-text-<%= @comment.id %>").html("<%= j render 'comments/edit_history_text', comment: @comment %>");