config/routes.rb
Rails.application.routes.draw do
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
    # member do
    #   delete 'delete_photo/:photo_id', action: 'delete_photo', as: 'delete_photo'
    # end
  end

  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  root to: 'pages#home'

  mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  acts_as_list
  has_one_attached :photo, dependent: :destroy
  validates :photo, content_type: [:png, :jpg, :jpeg]

  validates_presence_of :title, :body
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda {|attr| attr['name'].blank?}

  def self.by_position
    order("position ASC")
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
	before_action :set_portfolio_item, only: [:edit, :update, :show, :destroy]
	layout "portfolio"

	#petergate's access control
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

	def index
		@portfolio_items = Portfolio.by_position
	end

	def sort
		params[:order].each do |key, value|
			Portfolio.find(value[:id]).update(position: value[:position])
		end

		# don't look for a view to render
		render nothing: true
	end

	def new
		@portfolio_item = Portfolio.new
	end

	def create
		@portfolio_item = Portfolio.new(portfolio_params)

		respond_to do |format|
			if @portfolio_item.save
				 format.html { redirect_to portfolios_path, notice: 'Your portfolio item is now live.' }
			 else
				 format.html { render :new }
			 end
		 end
	end

	def show
	end

	def edit
	end

	def update
		respond_to do |format|
			if @portfolio_item.update(portfolio_params)
				format.html { redirect_to portfolios_path, notice: 'Item was successfully updated.' }
			else
				format.html { render :edit }
			end
		end
	end

	def destroy
		@portfolio_item.destroy
		respond_to do |format|
			format.html { redirect_to portfolios_path, notice: 'Item was successfully deleted.' }
		end
	end

	def delete_photo
		photo = ActiveStorage::Attachment.find(params[:photo_id])
		if current_user.site_admin?
			photo.purge
			redirect_back(fallback_location: request.referer)
		end
	end

	private
	def portfolio_params
		params.require(:portfolio).permit(:title, :subtitle, :body, :photo,
			technologies_attributes: [:id, :name, :_destroy])
	end

	def set_portfolio_item
		@portfolio_item = Portfolio.find(params[:id])
	end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload Image
          <%= f.file_field :photo, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>
  
  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>
    </div>

    <div>
      <%= link_to_add_association 'Add Technology', f, :technologies %>
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="col-md-4" >
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio_item.id %>">
    <% if portfolio_item.photo.attached? %>
      <%= image_tag portfolio_item.photo.variant(resize: '350x200!').processed %>
    <% end %>
    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio_item.title, portfolio_show_path(portfolio_item) %></span> <%= portfolio_item.subtitle %>
      </p>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>
  <%= link_to_remove_association 'Remove Item', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-form">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light" >
  <div class="container" >
      <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
        <%= render partial: 'portfolio_item', collection: @portfolio_items %>
      </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <% if @portfolio_item.photo.attached? %>
        <%= image_tag @portfolio_item.photo.variant(resize: '600x400!').processed, width: '90%' %>
        <% end %>
    </div>

    <div class="col-md-5">
      <h1><%= @portfolio_item.title %></h1>

      <hr>

      <em><%= @portfolio_item.subtitle %></em>

      <p><%= @portfolio_item.body %></p>

      <hr>


      <h3>Technologies Used:</h3>

      <% @portfolio_item.technologies.each do |t| %>
      <p><%= t.name %></p>
      <% end %>
      
      <div>
        <% if logged_in?(:site_admin) %>
          <div>
            <%= link_to "Edit Item", edit_portfolio_path(@portfolio_item), class: 'btn btn-warning' %>
          </div>
        <% end %><br/>
        <p>
          <%= link_to "View All Portfolio Items", portfolios_path, class: 'btn btn-warning' %> 
        </p>
      </div>
      
    </div>
  </div>
</div>